// generateName.ts
// This file is a tool to generate random names for towers.

const usernames = {
  firstNames: [
    'Creaky',
    'Grim',
    'Ticking',
    'Rusty',
    'Whirring',
    'Gargantuan',
    'Minuscule',
    'Ancient',
    'Eerie',
    'Mysterious',
    'Spectral',
    'Malevolent',
    'Haunted',
    'Sinister',
    'Ghastly',
    'Chiming',
    'Shadowy',
    'Cryptic',
    'Lurking',
    'Petrifying',
    'Clockwork',
    'Mechanical',
    'Gloomy',
    'Twisted',
    'Grotesque',
    'Rattling',
    'Bizarre',
    'Phantom',
    'Wailing',
    'Gruesome',
  ],
  lastNames: [
    'Timekeeper',
    'Chronomancer',
    'Cogmaster',
    'Bellringer',
    'Hourglass',
    'Winder',
    'Ticktock',
    'Pendulum',
    'Gearsnout',
    'Sundial',
    'Clockface',
    'Oscillator',
    'Springheel',
    'Dialsmith',
    'Numeral',
    'Hands',
    'Quartzfiend',
    'Sprocket',
    'Escapement',
    'Timegrasp',
    'Alarmclaw',
    'Calibrator',
    'Gearwraith',
    'Counter',
    'Balancewheel',
    'Chronoghost',
    'Hourhand',
    'Clockfiend',
    'Mainspring',
    'Torsion',
  ],
}

export const generateName = () => {
  const firstName =
    usernames.firstNames[
      Math.floor(Math.random() * usernames.firstNames.length)
    ]
  const lastName =
    usernames.lastNames[Math.floor(Math.random() * usernames.lastNames.length)]
  return `${firstName} ${lastName}`
}

const clocktowerAdjectives = [
  'ancient',
  'atomic',
  'bimonthly',
  'biweekly',
  'brief',
  'chronological',
  'circular',
  'contemporary',
  'cosmic',
  'daily',
  'digital',
  'durable',
  'early',
  'ephemeral',
  'eternal',
  'fast',
  'fleeting',
  'future',
  'grandfatherly',
  'hourly',
  'immediate',
  'infinite',
  'instant',
  'intermittent',
  'irreversible',
  'linear',
  'mechanical',
  'medieval',
  'millennial',
  'momentary',
  'monthly',
  'nocturnal',
  'obsolete',
  'occasional',
  'past',
  'perpetual',
  'portable',
  'precise',
  'prehistoric',
  'present',
  'punctual',
  'quartz',
  'quick',
  'relative',
  'retro',
  'rhythmic',
  'sandy',
  'seasonal',
  'secular',
  'short-lived',
  'simultaneous',
  'slow',
  'solar',
  'sundial-esque',
  'synchronized',
  'temporal',
  'timely',
  'timeless',
  'ticking',
  'towering',
  'transient',
  'twilight',
  'twilit',
  'universal',
  'vintage',
  'yearly',
  'youthful',
  'hourglass-like',
  'measured',
  'unending',
  'finite',
  'analog',
  'stately',
  'elusive',
  'frozen',
  'flowing',
  'historic',
  'measurable',
  'predictable',
  'watchful',
  'winding',
  'unmeasured',
  'unwatched',
  'unsynchronized',
  'lunar',
  'gregorian',
  'julian',
  'tick-tock',
  'zoned',
  'accelerated',
  'elongated',
  'fractured',
  'dilating',
  'compressed',
  'warped',
  'fragmented',
  'mortal',
  'immortal',
  'time-zone-bound',
  'second-hand',
]

const clocktowerNouns = [
  'second',
  'minute',
  'hour',
  'day',
  'week',
  'month',
  'year',
  'decade',
  'century',
  'millennium',
  'epoch',
  'era',
  'eons',
  'watch',
  'wristwatch',
  'sundial',
  'metronome',
  'stopwatch',
  'timer',
  'alarm',
  'bell',
  'tick',
  'tock',
  'gear',
  'hand',
  'dial',
  'pendulum',
  'cuckoo',
  'gong',
  'chime',
  'bezel',
  'face',
  'mechanism',
  'calendar',
  'chronometer',
  'quartz',
  'spring',
  'fusee',
  'escapement',
  'timezone',
  'meridian',
  'noon',
  'midnight',
  'dusk',
  'dawn',
  'solstice',
  'equinox',
  'anachronism',
  'horologist',
  'timekeeper',
  'timeline',
  'timepiece',
  'hourglass',
  'astronomical',
  'carillon',
  'belfry',
  'turret',
  'synchronize',
  'tempo',
  'rhythm',
  'waterclock',
  'clepsydra',
  'future',
  'past',
  'present',
  'temporality',
  'infinity',
  'moment',
  'juncture',
  'chronology',
  'eventide',
  'lunar',
  'solar',
  'sidereal',
  'twilight',
  'timelessness',
]

export const generateUsername = () => {
  const adjective =
    clocktowerAdjectives[
      Math.floor(Math.random() * clocktowerAdjectives.length)
    ]
  const noun =
    clocktowerNouns[Math.floor(Math.random() * clocktowerNouns.length)]
  return `${adjective}-${noun}`
}

export const generatePublicKey = (length: number) => {
  // pick x random nouns and adjectives from the lists
  // Combine the lists clocktowerAdjectives + clocktowerNouns
  const words = [...clocktowerAdjectives, ...clocktowerNouns]
  const publicKeyWords = []
  for (let i = 0; i < length; i++) {
    publicKeyWords.push(
      words[Math.floor(Math.random() * words.length)].toLowerCase()
    )
  }
  // Key should be word-word-word-word...
  const publicKey = publicKeyWords.join('-')
  return publicKey
}
